version: '2'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /var/data/jsfilebox_mongo/db:/data/db
    networks:
      - default
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    restart: always 
    environment:
      - DB_ADDR=mongo
    volumes:
      - ./files:/usr/share/nginx/html/files
    networks:
      - default
  web:
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    restart: always 
    volumes:
      - ./files:/usr/share/nginx/html/files
    networks:
      - neco_link
      - default
networks:
  neco_link:
    external: true 

