version: '2'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - /var/data/jsfilebox_mongo/db:/data/db
    networks:
      - default
  node:
    image: node:alpine
    restart: always 
    volumes:
      - ./src:/usr/src
      - ./public/files:/usr/share/nginx/html/files
      - /var/log/jsfilebox:/var/log/node
    working_dir: '/usr/src'
    command: npm start
    networks:
      - default
  nginx:
    image: nginx:alpine
    restart: always 
    volumes:
      - ./public:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
      - /var/log/jsfilebox:/var/log/nginx
    networks:
      - neco_link
      - default
networks:
  neco_link:
    external: true 

